# SPDX-FileCopyrightText: 2020-2021 Eduard Wolf
#
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  # github actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  # project
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
