# SPDX-FileCopyrightText: 2020-2023 Eduard Wolf
#
# SPDX-License-Identifier: Apache-2.0

[versions]
compileSdk = "33"
compose-compiler = "1.4.0-alpha02"
compose-library = "1.3.1"
kotlin = "1.7.21"

[libraries]
# gradle classpath plugins
android-build-tools-gradle = { module = "com.android.tools.build:gradle", version = "7.3.1" }
kotlinx-knit = { module = "org.jetbrains.kotlinx:kotlinx-knit", version = "0.2.3" }
# dependencies
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.6.1" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose-library" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-library" }
kotest-property = { module = "io.kotest:kotest-property", version = "5.5.5" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.6.4" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm", version = "1.4.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jmailen.kotlinter", version = "3.13.0" }
licensee = { id = "app.cash.licensee", version = "1.6.0" }
