# SPDX-FileCopyrightText: 2020-2024 Eduard Wolf
#
# SPDX-License-Identifier: CC0-1.0

naming:
  InvalidPackageDeclaration:
    rootPackage: 'net.edwardday.serialization.preferences'
    excludes: ["**/example/**"]
  MatchingDeclarationName:
    excludes: ["**/example/**"]
