name: Develop

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build library with Gradle
        run: ./gradlew :library:build

      - name: Build sample project with Gradle
        run: ./gradlew :sample:build

      # DO NOT MERGE test release upload
      - name: build library upload archives
        run: ./gradlew :library:dokkaJavadocJar :library:sourcesJar

      - name: create Github release
        id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true

      - name: Upload sources
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./library/build/libs/library-sources.jar
            asset_name: library-sources.jar
            asset_content_type: application/jar

      - name: Upload javadoc
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./library/build/libs/library-javadoc.jar
            asset_name: library-javadoc.jar
            asset_content_type: application/jar

      - name: Upload library
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./library/build/outputs/aar/library-release.aar
            asset_name: library-release.aar
            asset_content_type: application/jar
