# SPDX-FileCopyrightText: 2020-2021 Eduard Wolf
#
# SPDX-License-Identifier: Apache-2.0

name: Develop

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: REUSE compliance check
        uses: fsfe/reuse-action@v1.1

      - name: validation
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build
        run: ./gradlew build

      - name: Test publication
        run: ./gradlew publishSnapshotPublicationToMavenLocal
