# SPDX-FileCopyrightText: 2020-2021 Eduard Wolf
#
# SPDX-License-Identifier: Apache-2.0

name: Gradle version update

on:
  schedule:
    - cron: '0 6 * * *'


jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: update gradle
        uses: gradle-update/update-gradle-wrapper-action@v1.0.18
        with:
          repo-token: "${{ secrets.WORKFLOW_TOKEN }}"
          labels: "dependencies,gradle"
