name: Gradle version update

on:
  schedule:
    - cron: '30 9 * * *'


jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update gradle
        id: gradleUpdate
        run: .github/scripts/update-gradle-version.sh

      - name: create pull request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          base: "test_gradle_version_check"
          commit-message: "Update gradle to ${{ steps.gradleUpdate.outputs.gradleVersion }}"
          branch: "gradle_update/version_${{ steps.gradleUpdate.outputs.gradleVersion }}"
          delete-branch: true
          title: "Update gradle to ${{ steps.gradleUpdate.outputs.gradleVersion }}"
          body: |
            New [gradle version ${{ steps.gradleUpdate.outputs.gradleVersion }}](https://docs.gradle.org/${{ steps.gradleUpdate.outputs.gradleVersion }}/release-notes.html)

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          labels: "dependencies,gradle"
