name: Gradle version update

on:
  push:
    branches:
      - "trigger_workflow_after_gradle_upgrade_test"


jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update gradle
        id: gradleUpdate
        uses: EdwarDDay/upgrade-gradle-action@v1.2.1

      - name: create pull request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          # cannot trigger other workflow with default token, so use another token
          # https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: "${{ secrets.WORKFLOW_TOKEN }}"
          base: "trigger_workflow_after_gradle_upgrade_test"
          draft: true
          commit-message: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          branch: "gradle_update/version_${{ steps.gradleUpdate.outputs.gradle-version }}_test"
          delete-branch: true
          title: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          body: |
            New [gradle version ${{ steps.gradleUpdate.outputs.gradle-version }}](https://docs.gradle.org/${{ steps.gradleUpdate.outputs.gradle-version }}/release-notes.html)

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          labels: "dependencies,gradle"
