name: Gradle version update

on:
  pull_request:


jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update gradle
        id: gradleUpdate
        uses: EdwarDDay/upgrade-gradle-action@v1.0.1
        with:
          distribution-type: all
          release-channel: release-candidate

      - name: create pull request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          commit-message: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          branch: "gradle_update/version_${{ steps.gradleUpdate.outputs.gradle-version }}"
          delete-branch: true
          base: main
          title: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          body: |
            New [gradle version ${{ steps.gradleUpdate.outputs.gradle-version }}](https://docs.gradle.org/${{ steps.gradleUpdate.outputs.gradle-version }}/release-notes.html)

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          labels: "dependencies,gradle"
