name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set VCS tag
        id: variables
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Upload to maven central
        run: ./gradlew :library:signReleasePublication
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeNexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPENEXUSUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypeNexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPENEXUSPASSWORD }}
          VCS_TAG: ${{ steps.variables.outputs.tag }}
