# SPDX-FileCopyrightText: 2020-2024 Eduard Wolf
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set VCS tag
        id: variables
        run: echo "tag=${GITHUB_REF#refs/*/}"

      - name: set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to maven central
        run: ./gradlew :library:publishReleasePublicationToMavenCentralRepository
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeNexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPENEXUSUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypeNexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPENEXUSPASSWORD }}
          VCS_TAG: ${{ steps.variables.outputs.tag }}

      - name: create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: false
          files: |
            ./library/build/libs/library-sources.jar
            ./library/build/libs/library-javadoc.jar
            ./library/build/outputs/aar/library-release.aar

  docs:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build html documentation
        run: ./gradlew :library:dokkaHtml

      - name: Upload html documentation
        uses: JamesIves/github-pages-deploy-action@v4.6.6
        with:
          branch: gh-pages
          folder: library/build/dokka/html
